spring:
  rabbitmq:
    host: 192.168.3.128
    port: 5672
    virtual-host: /
    username: Javon
    password: 12345
    listener:
      simple:
        prefetch: 1 #消费预取 限制 >> 每次只能获取一条消息，处理完成才能获取下一个消息