seata:
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      username: nacos
#      password: nacos
#      group: SEATA_GROUP
#      data-id: client.properties
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server-tc # tc服务在nacos中的服务名称
      username: nacos
      password: nacos
  #      cluster: SZ
  tx-service-group: seata-demo # 事务组，根据这个获取tc服务的cluster名称
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      seata-demo: SZ
  data-source-proxy-mode: XA #开启数据源代理XA模式



feign:
  httpclient:
    enabled: true
    connection-timeout: 300000
    max-connections: 200
    max-connections-per-route: 50


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: Publish.pojo
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto